### ISSUE TITLE
Spell Point Progression doesn't work for Subclasses

### ISSUE THREAD

**Issue by bwizz245** [misthero/dnd5e-spellpoints#100]
![1](https://github.com/misthero/dnd5e-spellpoints/assets/154015213/915972de-344f-4c54-a8b3-be7f90dc2e36)
![2](https://github.com/misthero/dnd5e-spellpoints/assets/154015213/f4bc0daa-f139-447b-a8dd-ee9748d6c020)
![3](https://github.com/misthero/dnd5e-spellpoints/assets/154015213/ea94c7a0-3a6a-44c5-9ece-616d4ab0cfe0)

I've attempted to make a spellcasting subclass for a non-spellcasting class (specifically Eldritch Knight, but I've also tried it with Arcane Trickster) using spell points, but when I actually create a character with the subclass, the module doesn't seem to detect it and update the spell points. It just stays at 1, no matter what their level is.

I thought it might have to do with the subclass being a Third Caster, but it doesn't work no matter which spell progression setting I use. There are no errors in the console when adding the subclass/feature to the character and no message in chat indicating that the Spell Points item has been detected.

Is there any way for me to get this to work, or does the module just not work for Subclasses right now?

**Comment by misthero** [comment]
I think you should grant slots to your subclass, since the module looks to the spellslots object to understand the spell level you can cast, also the slot object carry with it the information about what kind of caster that is, first, second, third, pact, artificier etc.. It doesn't really care if you have a certain class or not.

**Comment by bwizz245** [comment]
If you're referring to the Spellcasting section of the subclass item, you can see in my first screenshot that I've already properly set that up. When I add the subclass to a character with the shown settings, it gets the proper amount of spell slots.

**Comment by misthero** [comment]
> If you're referring to the Spellcasting section of the subclass item, you can see in my first screenshot that I've already properly set that up. When I add the subclass to a character with the shown settings, it gets the proper amount of spell slots.

ok, then check how many spell points he should have? 

at level 3 he is a level 1 caster

this table show the character level on the left and the corrisponding "Spellcaster Level" for each type of caster

|Character Level | Full | Half | Third|
|-- | -- | -- | --|
|1 | 1 | - | -|
|2 | 2 | 1 | -|
|3 | 3 | 2 | 1|
|4 | 4 | 2 | 2|
|5 | 5 | 3 | 2|
|6 | 6 | 3 | 2|
|7 | 7 | 4 | 3|
|8 | 8 | 4 | 3|
|9 | 9 | 5 | 3|
|10 | 10 | 5 | 4|
|11 | 11 | 6 | 4|
|12 | 12 | 6 | 4|
|13 | 13 | 7 | 5|
|14 | 14 | 7 | 5|
|15 | 15 | 8 | 5|
|16 | 16 | 8 | 6|
|17 | 17 | 9 | 6|
|18 | 18 | 9 | 6|
|19 | 19 | 10 | 7|
|20 | 20 | 10 | 7|

**Comment by misthero** [comment]
oh wait are you using default DMG as the formula, maybe I found a problem there. will get back to you

**Comment by misthero** [comment]
may you check the latest version?

**Comment by bwizz245** [comment]
It's working now, thanks
