### ISSUE TITLE
NPC Spell point

### ISSUE THREAD

**Issue by Agentblank66** [misthero/dnd5e-spellpoints#102]
When you give an NPC sheet the Spellpoint feat, the spellpoint bar don't show up and the spellpoint don't increase as I increase the caster level.

**Comment by misthero** [comment]
both those things are not supposed to happen, npcs doesn't level up, the spell point bar is not implemented at all on pnc sheet. If you need to change an npc level or something, when you finish creating your custom npc and everything is ready, remove the spellpoint item and drop on it a new one, it should update.

**Comment by Agentblank66** [comment]
That worked thanks
