### ISSUE TITLE
D&D ver. 4.0.0 

### ISSUE THREAD

**Issue by MaxSilDire** [misthero/dnd5e-spellpoints#103]
![BUG spell](https://github.com/user-attachments/assets/4e4feb2b-029b-496f-8500-f5df8cf109ec)
Hi. The module no longer works on the new version of D&D 4.0.0. It gives an error in the console. Please update when you have time. :)
Thanks for this module, I use it on a regular basis in my games.

**Comment by misthero** [comment]
discovered today that v4 was out, will update ASAP

**Comment by misthero** [comment]
try latest version v2.4.00

it needed a lot of work, let me know if you find any issue

**Comment by ciscowicaksana** [comment]
![image](https://github.com/user-attachments/assets/16242d5b-fd0d-4abb-883d-26517d64d92d)
Hiya I have updated to the newest version but it seems like there is a setting somewhere that disables activating the module.

**Comment by misthero** [comment]
> I just updated to the newest version but it seems like there is a setting somewhere that disables activating the module.

sorry, my bad, the previous release had a wrong manifest link, please install manually entering this manifest url

https://github.com/misthero/dnd5e-spellpoints/releases/latest/download/module.json

![immagine](https://github.com/user-attachments/assets/e939436e-13e7-481c-ad87-53f6fd561867)

**Comment by ciscowicaksana** [comment]
No problem. I already used the auto-updater it now already asks to switch manifest URL automatically. Thanks once again. Keep up the good work~
