### ISSUE TITLE
In V2.4.11 

### ISSUE THREAD

**Issue by Agentblank66** [misthero/dnd5e-spellpoints#107]
I can't enable the module in my world, when I press the save button.

**Comment by misthero** [comment]
do you see any error in console?

**Comment by misthero** [comment]
to open the browser console use F12 and keep it open while trying to enable the module. 

check if any errors pops out than

**Comment by Agentblank66** [comment]
I'm used the filter to look for "spellpoints"

**Comment by misthero** [comment]
that's not it, as you can see the message comes from "foundry.js"

errors usually have a RED background color like this:

![immagine](https://github.com/user-attachments/assets/0a673e3d-c8d2-4df4-84d6-9b52deaf226e)

**Comment by Agentblank66** [comment]
The only two errors I get is these two:

![image](https://github.com/user-attachments/assets/2e5b9a76-3d4f-4af3-bbc2-f635daec49b8)

**Comment by misthero** [comment]
wait, are you on dnd version 3.3.1?

**Comment by misthero** [comment]
spellpoints v2.4+ can only be enabled on dnd v4+

**Comment by Agentblank66** [comment]
Yes, I just updated the modules that was compatible with my version

**Comment by misthero** [comment]
Foundry compatibility only check the foundry version when updating, not system version.

 you need v2.2.33 : https://github.com/misthero/dnd5e-spellpoints/releases/tag/v2.2.33
 
 install manually using the following manifest url:
 `https://github.com/misthero/dnd5e-spellpoints/releases/download/v2.2.33/module.json`
 
than **right click** on the module and finally **lock it** so it doesn't get automatically updated until you decide to update dnd system too
 
 
![immagine](https://github.com/user-attachments/assets/268dcfb8-afde-4f4c-a9bb-ccd2b8976589)

**Comment by Agentblank66** [comment]
Thank you for the help.

**Comment by misthero** [comment]
you are welcome, have fun!
