### ISSUE TITLE
Spell Points not working in legacy version

### ISSUE THREAD

**Issue by KolIBS** [misthero/dnd5e-spellpoints#110]
I'm using Foundry v12.331 and DnD 5e v3.3.1 (this is the latest version with which the Plutonium mod is compatible; I consider Plutonium an essential mod so updating my 5e system is not an option unfortunately). I have installed dnd5e-spellpoints v2.2.33 as that was the last version that maintained DnD 5e v3.X compatibility; I can drag the spell points feature onto carachter sheets, but when casting a spell have no option to use spell points instead of spell slots. Is there anything I might have missed or is the module working improperly?

**Comment by KolIBS** [comment]
I screenshotted the errors I see as copy/pasting had unsightly results:

![Screenshot 2024-11-21 132242](https://github.com/user-attachments/assets/448a93c2-6baf-4f96-ac20-e6714e1abe87)

![Screenshot 2024-11-21 132313](https://github.com/user-attachments/assets/6d2d5aa4-cc96-4577-937d-0ac32d65361a)

**Comment by misthero** [comment]
ok, i see some warning and 1 error, but is not relates with the spellpoints module. try keepeng the console open and do something like dropping the spellpoints item on the character sheet or casting a spell and check if some error appears during those operations

**Comment by KolIBS** [comment]
No error appears when casting a spell. When I click the spell points feature on the character sheet, the following appears in the dialogue tab:

![Screenshot 2024-11-21 141431](https://github.com/user-attachments/assets/e68a52b6-e3ae-4b70-9f60-3c0a0862bb51)

If I click "Consume Usage" nothing happens and nothing shows up in the console. If I click it again, I get an error saying:

"Spell points has no available uses remaining.  foundry.js.72076"

Also, while the spell points feature appears on the character sheet, there is no bar

![Screenshot 2024-11-21 141942](https://github.com/user-attachments/assets/b6ac32ac-ae59-49e8-b139-6369b05b87be)

**Comment by misthero** [comment]
I just tested a new installation with foundry v12, spellpoints v 2.2.33 and dnd v3.3.1. Everything works.

did you enabled the module in settings?

![immagine](https://github.com/user-attachments/assets/65512a3f-6c0f-4770-8bfc-8ed490bd8cd7)

if not try creating a new world, it could be another module preventing it to function

**Comment by KolIBS** [comment]
Omg I feel like an idiot thank you so much! I didn't think I would need to turn on the module after installing it. All set!
