### ISSUE TITLE
The module prevents spells from consuming resources other than the one set.

### ISSUE THREAD

**Issue by AquaZera** [misthero/dnd5e-spellpoints#13]
I disabled all other mods. I tried making a spell consume the spell point resource in addition to another resource. When the spell point module is disabled the spell consumed the other resource like normal, but when enabled the other resource would never decrease.

**Comment by misthero** [comment]
Good catch @AquaZera, I have pulled a patch (not yet published on fvtt) can you test it?
you should download the module from here and replace the one you have. 

Thank you

**Comment by AquaZera** [comment]
I just tested it, and it works splendidly.
