### ISSUE TITLE
Hide Configuration Button When Sheet is Locked

### ISSUE THREAD

**Issue by VoltCruelerz** [misthero/dnd5e-spellpoints#14]
Considering the dramatic effect this has based on this being enabled or disabled, I believe the config option should be hidden (or at least disabled) when the sheet is locked.

![image](https://user-images.githubusercontent.com/4068550/128176222-69943fdf-cde5-4597-8fbd-dc6d66aaea65.png)

**Comment by misthero** [comment]
Just pulled the changes so the checkbox is disabled when sheet is locked
