### ISSUE TITLE
Change instances of "his" to "their" (English)

### ISSUE THREAD

**Issue by cobaltw** [misthero/dnd5e-spellpoints#15]
Instances of "his" should be changed to "their" for the sake of covering different genders, or genderless characters (warforged, for example).
I usually change this myself in the en.json lang file, but I'd appreciate not having to reapply my changes when the module updates.

For example:
Change "{ActorName} casted using **his** own life losing {hpMaxLost} Maximum Hit Points"
to "{ActorName} casted using **their** own life losing {hpMaxLost} Maximum Hit Points"

**Comment by misthero** [comment]
closing
