### ISSUE TITLE
Bug: Character has "Uses Spell Points" in Tidy5e when it does not

### ISSUE THREAD

**Issue by MrVauxs** [misthero/dnd5e-spellpoints#19]
As the title says, when you lock the sheet the text that a character uses spell points only gets greyed out with the text 
![image](https://user-images.githubusercontent.com/32039708/137418824-7fa7e21d-6487-4cc8-9c90-0ead9fd8d572.png) which implies the actor does use spell points even if the setting is turned off.

**Comment by mflaherty97** [comment]
This issue seems to still be present. Any updates one this?

**Comment by misthero** [comment]
what version are you on @mflaherty97 I can't reproduce the issue on the latest 1.3.1

**Comment by MrVauxs** [comment]
> what version are you on @mflaherty97 I can't reproduce the issue on the latest 1.3.1

Version 9, dnd5e 1.5.7
Advanced Magic 1.3.1
Tidy5e Sheet 0.5.21

The text still persists despite it being disabled
![image](https://user-images.githubusercontent.com/32039708/150143537-f3a5c82b-f667-4a29-a33b-7e324d5739ba.png)

![image](https://user-images.githubusercontent.com/32039708/150143468-73237711-7874-4b5d-b471-839924908831.png)

**Comment by misthero** [comment]
what do you mean being disabled? did you unchecked mixed mode in module settings?

**Comment by misthero** [comment]
check [here](https://github.com/misthero/dnd5e-spellpoints/issues/14)

**Comment by MrVauxs** [comment]
The issue is the fact that when the sheet is locked, it says that **This character uses Spell Points** when the character *does not*.

**Comment by mflaherty97** [comment]
Ignore my previous. I had my sheet locked like a doofus. Thank you
