### ISSUE TITLE
Automatic SP

### ISSUE THREAD

**Issue by MrBrentRogers** [misthero/dnd5e-spellpoints#2]
Does the system automatically give you spell points by level or do we need to manually put in the correct number of spell points for the caster level?

Instructions are a bit vague

**Comment by misthero** [comment]
You are right, I' didn't mentioned it in the instructions, that would be a nice feature but at the moment the module just calculate the spell cost you are casting and subtract the correct number of spellpoints.

**Comment by misthero** [comment]
Now the module automatically give you spell points by level :)
