### ISSUE TITLE
Chat Message when spell is cast.

### ISSUE THREAD

**Issue by Opzehn** [misthero/dnd5e-spellpoints#25]
I can't see an option in the module settings to disable the message being sent to the chat when you cast a spell.
Is there a possibility of requesting such a feature?
Thanks.

**Comment by Zanderaf** [comment]
Yea, I'd like to hide what level of spell the NPC is casting, and the casting itself-

**Comment by misthero** [comment]
> I can't see an option in the module settings to disable the message being sent to the chat when you cast a spell. Is there a possibility of requesting such a feature? Thanks.

this should be possible with the new version.
