### ISSUE TITLE
Spell points does not work well with multiclassing with warlocks

### ISSUE THREAD

**Issue by CrackJackFlood** [misthero/dnd5e-spellpoints#29]
https://github.com/misthero/dnd5e-spellpoints/issues/28#issue-1222523373

I am having this issue

**Comment by CrackJackFlood** [comment]
> [#28 (comment)](https://github.com/misthero/dnd5e-spellpoints/issues/28#issue-1222523373)
> 
> I am having this issue

It seems like the bug stems from the fact pact slots are treated like spell shots.

**Comment by CrackJackFlood** [comment]
I have investigated it to the best of knowledge, it seems the issue is squarely related to something related to warlock spellcasting and pacts I assume this issue popped up as a result of DnD5e system updating.

**Comment by misthero** [comment]
Thank you for reporting it, I'll investigate as soon as I can, meanwhile can you describe exactly what you mean with "does not work well with multiclassing with warlocks"?
That is: what are the steps to reproduce the issue, what is the expected result an what happens instead? also your foundry version.

Thank you.

**Comment by CrackJackFlood** [comment]
> Thank you for reporting it, I'll investigate as soon as I can, meanwhile can you describe exactly what you mean with "does not work well with multiclassing with warlocks"? That is: what are the steps to reproduce the issue, what is the expected result an what happens instead? also your foundry version.
> 
> Thank you.



> I have investigated it to the best of knowledge, it seems the issue is squarely related to something related to warlock spellcasting and pacts I assume this issue popped up as a result of DnD5e system updating.
> 
> I have tested Foundry V9, DnD5e. This module being the only one being loaded.
> 
> Steps to recreate issue -
> 
> Create character, create class, select warlock spellcasting, create spell and set it as pact magic, cast the spell prompt will ask what slot you would like to consume the only option will be undefined.

So basically pact slots are treated like spell slots, and are undefined like https://github.com/misthero/dnd5e-spellpoints/issues/28#issue-1222523373 - There is no way to cast pact spells with pact spell slots as it just uses spell points. I have been testing it on and off all day nothing I could do to get it too work and no errors are in the console. 

![image](https://user-images.githubusercontent.com/49882452/171302757-0d2a325c-46e1-4bd3-8cb2-119bcf158105.png)

I tested with DnD 1.5.7 the issue is not there. So the issue to related with latest DnD 1.6.X update. My thinking im not a programmer I only understand the js syntax at the basic level the issue lies with how warlock "classes" and "pact spells/slots" Its probably best to also check that all the other casting classes are being handled properly as well like 1/2, 1/3 and artificer casters.

Another issue I have noticed is that when you add a spell to the spell sheet or update a spell your spell points are reduced like you have just cast the spell at max level.

Another issue the "gritty" option for allowing hp to be used when out of spell points is pretty borked when you level you up it prevents health from levelup being applied to the character.

**Comment by misthero** [comment]
ok I'm going to reopen https://github.com/misthero/dnd5e-spellpoints/issues/28

please continue this issue there, also for the "gritty" bug I ask you to open a different issue with details so we can track everything correctly.

Thank you again.
