### ISSUE TITLE
Create Spell Points versions of Spell Progression systems

### ISSUE THREAD

**Issue by MrVauxs** [misthero/dnd5e-spellpoints#3]
Currently switching the module and option to have Spell Points on, causes using the other option, Spell Slots, to cause errors.
This proves to be less than ideal for homebrew that gives only one class Spell Points (such as [Variant Sorcerer by devikyn](https://drive.google.com/file/d/15xiad-Kj0NifJ0y_YydN7ZbjZUXyibiE/view)) while everyone else keeps Spell Slots.

I believe you could hit two birds with one stone (allowing for use of both Spell Slots and Spell Points in one game **and** in one character sheet) by making it a the following two things, rather than just a global setting:

- It's own Spell Progression (Full, Half, 1/3 Caster)
![image](https://user-images.githubusercontent.com/32039708/100528100-3dd58600-31d9-11eb-98df-07cbe49ec71c.png)

- An option for Spells so it gets moved to the new progression system
![image](https://user-images.githubusercontent.com/32039708/100528078-049d1600-31d9-11eb-9de8-0ad67470cfdd.png)

In FoundryVTT sense, this can already be done(ish) by using the Spell Slot counter to track Spell Points, which would leave only the name and spell costs to be modified.
![image](https://user-images.githubusercontent.com/32039708/100528025-63ae5b00-31d8-11eb-8e5e-158bb6b3dc2e.png)

**Comment by misthero** [comment]
that's actually a good idea, i have released a rough version of mixed mode, the logic of the module are pretty different from what you imagine there, it is probably doable, but that would need a lot of work and character sheet modifications.

**Comment by MrVauxs** [comment]
Indeed this is more of a 2.0 project, but nontheless, a suggestion to be considered.

**Comment by misthero** [comment]
meanwhile have you had a chance to try the new version? let me know if that works for you

**Comment by MrVauxs** [comment]
> meanwhile have you had a chance to try the new version? let me know if that works for you

It works splendid. Though if I were to make another suggestion, I would move the button from **Spellbook** to **Special Traits**.

**Comment by MrVauxs** [comment]
This has been done with [Spellpoints5e](https://github.com/Mary-Usagi/spellpoints5e) module.
