### ISSUE TITLE
Reference Costs No Longer Work

### ISSUE THREAD

**Issue by VoltCruelerz** [misthero/dnd5e-spellpoints#30]
With the most recent update, reference costs like the following no longer work. They're just treated as 0.

![image](https://user-images.githubusercontent.com/4068550/171878194-0a681b19-7e1c-450b-a8e4-b049402856e5.png)

(I was using this as a workaround for #26.)

**Comment by misthero** [comment]
hi, the cost calculation has not changed, where that **owlmarble-magic** flag comes from?
another module maybe?

**Comment by VoltCruelerz** [comment]
I added those flags with a one-off script I wrote a while back. I can validate that the flag is still set though. It's even still accessible through more conventional means:

![image](https://user-images.githubusercontent.com/4068550/171910123-b119fa79-4dcb-4832-804c-adcc04aef5a5.png)

In testing, I can see that I can still set spell point costs to other references like `@abilities.cha.value`. Upon testing with other flags, I find they don't work either.

In Data Inspector, I can see that flags are part of Roll Data, but not Source or Derived.

![image](https://user-images.githubusercontent.com/4068550/171911965-4b914bae-64ca-4a86-9458-a2b6bbdf811b.png)

If things didn't change on your end, did the 5e system itself change in some way, do you know?

**Comment by misthero** [comment]
yes, 5e system introduced some breaking changes in version 1.6+

this could be another one

**Comment by VoltCruelerz** [comment]
Well, I installed an older version of your mod and the problem persisted, so I guess this must have been introduced in 5e 1.6.2, because it was fine for 1.6.1.

Closing.

**Comment by misthero** [comment]
I've talked with dnd5e developers about this, the say that flags have never been available in the roll data this module was passing for formula evaluation.
Probably you had some other module messing around, anyway I don't see why flags shoudnt be available so I made a modification to the funcion that evaluates the formula including the flags object.

Now your formula should work. (v 1.3.7)
