### ISSUE TITLE
Manifest URL problem _Maybe_

### ISSUE THREAD

**Issue by caprichozow** [misthero/dnd5e-spellpoints#32]
The module is not installing through the manifest URL (Version 1.3.7) or through Foundry, I believe the current link for it is under /main/ instead of /FVTT-V9/
https://raw.githubusercontent.com/misthero/dnd5e-spellpoints/FVTT-V9/module.json
I got it to install with this manifest link instead!

**Comment by misthero** [comment]
FVTT-V9 branch is the foundry v9 compatible branc. Main branch is for Foundry v10+ now
