### ISSUE TITLE
No cast warning when 0 spell points

### ISSUE THREAD

**Issue by Orionox** [misthero/dnd5e-spellpoints#34]
No warning is issued in chat when a character has 0 spell points. The warning works fine when low on spell points, but not when at 0. Additionally, the gritty version does not appear to be working as no health is removed from the character sheet when casting a spell at 0 spell points.

**Comment by misthero** [comment]
Hello, sorry for the late answer, I cannot reproduce the issue on a clean world.

**Comment by misthero** [comment]
![immagine](https://user-images.githubusercontent.com/3662610/198842796-49b9a43a-5fba-4049-97b7-995da2162210.png)

Module version is: 1.4.0
Foundry Version is: 10 Build 288
DnD 5e System Version is: 2.0.3

**Comment by Orionox** [comment]
I'm currently out of town, but when K get home I'll do some investigating
and get back to you.
