### ISSUE TITLE
Custom without formula

### ISSUE THREAD

**Issue by ArcaneFired** [misthero/dnd5e-spellpoints#40]
Not really an issue, but i was wondering if there was a way to have points set to whatever I want without it needing to be formula based?

The points I want to use do not scale based on any current measure and it all custom

**Comment by misthero** [comment]
it is not clear for me if you are talking about the formula to calculate how many spell points a character get from it's class or lever, or the formula to calculate the spell point cost for each slot when you cast a spell..

you can ignore the automatic spell point calculation when your character level up and set the number od spell points to anything you want directly editing the resource.

and about of the cost in spell point for each spell level it can be anything, you can set it to 100 for first level spells and 54 for 9th level spells..

can you give me an exhample?
