### ISSUE TITLE
I'm trying to use your spell points as a Psionic Point system. to add psionic abilities to my caster and non-caster players

### ISSUE THREAD

**Issue by Ringelrun** [misthero/dnd5e-spellpoints#41]
I'd like to be able to toggle to spend spell slots for spells, and then Psionic (spell) points for the Psionic abilities. But not have any spell slots get expended when using the points, and also to not have the number of available spell slots change after the casting of the Psionic ability (when using the points). It seems like an all or nothing currently and then it refills the spell slots to full (which is like everyone gets a free long rest because they cast an ability with a point)

**Comment by misthero** [comment]
I don't know if i get the request, at the moment the module replace the slots with spell points. this can be done globally or on every character sheet indipendently.

you want to be able to switch between spell points and slots? or you want two different spell points pools?
