### ISSUE TITLE
Custom Point editor not opening

### ISSUE THREAD

**Issue by JMPizana** [misthero/dnd5e-spellpoints#44]
Hi, I'm trying to set a custom spell point scaling as I've been able in the past, but when trying to change the value in the dropdown to any of the custom formulas this error arises in the console.

![image](https://user-images.githubusercontent.com/22452324/222559294-223a2624-d251-4fc8-9950-ba04a9e96591.png)

```
dnd5e-spellpoints.js:659 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at SpellPointsForm._onChangeInput (dnd5e-spellpoints.js:659:51)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

I've replicated the issue in a world with just this module and the one forcibly active by Forge VTT. My world info is this:

![image](https://user-images.githubusercontent.com/22452324/222559076-9d9f7c74-9ba0-4172-bb3d-e52994959deb.png)

**Comment by misthero** [comment]
good catch, I missed that.

Please update to fix.

**Comment by JMPizana** [comment]
So fast!! 🤩 Thank you!

**Comment by JMPizana** [comment]
I've re-opened the panel and it works.
