### ISSUE TITLE
Spell Points not being seen

### ISSUE THREAD

**Issue by GM-Bif** [misthero/dnd5e-spellpoints#45]
Whenever I try to cast a spell using this mod, it says I do not have enough spell points even when I'm at full.

To elaborate, I am using the advanced system with the hp option on.  I have tried disabling my other mods and the problem still occurs.  I've reinstalled and updated a couple of times.

**Comment by misthero** [comment]
I don't know if it's intended or not, but new 5e system is not passing anymore the resource value when it is 0, so the module get "undefined". 

anyway, should be fixed, please update.
