### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by Joebobio** [misthero/dnd5e-spellpoints#47]
Hey, not sure if I'm doing something wrong but I can't get the spell points to work even after disabling every other module. 
I can enable the module and check the box to turn it on, but no changes appear on my spellcasters' sheets.
Any ideas? Should I try something else? I'm fairly new to Foundry. I have 20 active modules currently.
I'm using dnd5e 2.1.5, and I have the most up to date version of this module. 

Thanks a bunch!

**Comment by misthero** [comment]
Did you created the spell point resource?

please read https://github.com/misthero/dnd5e-spellpoints/blob/main/README.md

**Comment by Joebobio** [comment]
Yes. I created the resources on all of the PCs character sheets
![q1](https://user-images.githubusercontent.com/127917953/225946199-55fe06b0-78c6-4782-ac90-98c18ae812d0.JPG)
![q2](https://user-images.githubusercontent.com/127917953/225946212-30be37d9-2fab-426e-b4a4-931252bbda99.JPG)

**Comment by misthero** [comment]
I see you have 0 spellpoints, fill that resource (or level up if you are using the automatic calculation) and cast a spell that would use a spell slot. You should see the spell point resource decreasing.

**Comment by Joebobio** [comment]
I will try that when I get home and let you know!

**Comment by Joebobio** [comment]
This worked. Thanks a bunch
