### ISSUE TITLE
Hidden NPC's cannot be seen in GM combat tracker (FVT 0.7.8 DND5e 1.2)

### ISSUE THREAD

**Issue by Lyvewyrez** [misthero/dnd5e-spellpoints#5]
Hello,

Loving the module, but have an issue where hidden NPC's should show up as hidden for the GM like the image attached, however with your mod enabled (tested with just this mod), anything that gets added to the tracker while hidden, or gets hidden by clicking the button, is visually removed from the combat tracker for the GM as well. Instead, it shows up as the second image, where there is an entity in the combat tracker, but it cannot be interacted with. 
Turning on/off the 'Enable Spell System' doesn't change this from what I have tested, nor does anything else in the module settings, only disabling the module brings back the 'hidden' entity inside the combat tracker.

If you are able to resolve this issue, would greatly appreciate it! I would like to keep using the module, but cannot use it at the moment for the above reason, though I'm wondering why no one else has had the same problem. I was curious if it may have been a conflict, but as mentioned, had just this module active and it was still doing it. Have a feeling that maybe it is something that got updated in 0.7.8 Foundry which could be causing this to happen (which is the version I am currently running).  

![image](https://user-images.githubusercontent.com/48006774/103059834-bc152480-45ed-11eb-9757-67db4f5fca84.png)
![image](https://user-images.githubusercontent.com/48006774/103059957-2a59e700-45ee-11eb-889c-ad1c63a5b509.png)

**Comment by fyre4000** [comment]
I have the same issue. I'm not sure, but I think I was having it before the update? Once again, not sure, but glad I'm not alone with this issue.

**Comment by misthero** [comment]
Thank you guys for the report, it should be fixed in the last update:
https://github.com/misthero/dnd5e-spellpoints/commit/da492e06e3aae311d55bdbb6389242613234ba55

please update the module from foundry VTT
