### ISSUE TITLE
Update for DnD 5e 2.4.0

### ISSUE THREAD

**Issue by OxTailSafu** [misthero/dnd5e-spellpoints#56]
Hello there, this has been extremely useful for our table so thank you so much for making it! I'm curious if there were any plans to update this module for the newest version of 5e that was just recently released. I've heard that this module sadly isn't compatible with it which makes updating an impossibility at this time.

**Comment by tkmehta** [comment]
I was able to get a temporary workaround [here](https://github.com/misthero/dnd5e-spellpoints/issues/57#issuecomment-1836785217).
