### ISSUE TITLE
Update for Foundry V11.315 and DND 5e v2.4.0

### ISSUE THREAD

**Issue by Gierolier** [misthero/dnd5e-spellpoints#57]
Spell points system with current updates allows for resources to be named (to default spell points or custom name) but will not override spell slots nor utilize spell points when casting spells.
![image_2023-11-26_113645916](https://github.com/misthero/dnd5e-spellpoints/assets/67870753/3a3a10c5-14d7-4122-88ee-ce40b46e9d43)
![image](https://github.com/misthero/dnd5e-spellpoints/assets/67870753/d88d808a-5b1e-4ab9-9404-57d85975b3d1)

**Comment by tkmehta** [comment]
I was able to make it work for myself by a few simple edits to the 'spellpoints.js' file. As a disclaimer, I'm not really an expert at JQuery so your mileage may vary.

- Find and replace every instance (there should be 5 total) of `consumeSpellLevel` with `slotLevel`
- On line 320, replace `selectValue` with `selectValue.match(/\d+/)[0]`

**Comment by misthero** [comment]
thank you, can you try the latest version?
