### ISSUE TITLE
Mixed Mode doesn't allow for disabling spell points.

### ISSUE THREAD

**Issue by fyre4000** [misthero/dnd5e-spellpoints#6]
When you turn on the mixed mode option, there should be a check box on the spellbook page that says "this character uses spell points". However, the checkbox has been replaced with an effect symbol, and can't be disabled.
![image](https://user-images.githubusercontent.com/43389274/103114152-9149c100-462b-11eb-9648-d5b0cae1ad13.png)
This has been tested with no modules enabled other than Spell Points, and the issue still persists. Any help would be appreciated.

**Comment by misthero** [comment]
Thank you I introduced that bug yesterday fixing something else, now it should work. Update the module!
