### ISSUE TITLE
CONFIG.debug.hooks = true left on.

### ISSUE THREAD

**Issue by Demonkiller8973** [misthero/dnd5e-spellpoints#74]
Just wanted to let you know in your scripts\main.js file you left
"CONFIG.debug.hooks = true"
This causes the Foundry Console to be flooded with DEBUG notifications for everything.

Thanks, love the Mod!

**Comment by misthero** [comment]
thanks, tou are right, will fix next release.

**Comment by misthero** [comment]
done
