### ISSUE TITLE
Mixed System?

### ISSUE THREAD

**Issue by mflaherty97** [misthero/dnd5e-spellpoints#78]
Only some of my PCs use spell points. The majority of them use slots. Its confusing to the ones with spell points that a dialogue box shows up saying "You don't have any slots." And its confusing to the ones that use spell SLOTS that a dialogue box shows up saying "Create a resource named spell points."
Is there a way that I could assign certain PCs to use spell points or spell slots so that the module knows when to put up a dialogue box?

**Comment by mflaherty97** [comment]
The latest version I believe? 2.0.1

**Comment by mflaherty97** [comment]
![image](https://github.com/misthero/dnd5e-spellpoints/assets/97583315/0e514dfa-db72-4cd3-89da-d0fc0bc939be)
This actor uses spell slots.
![image](https://github.com/misthero/dnd5e-spellpoints/assets/97583315/b62ce5e2-4008-4f45-a0d7-98e02583629c)
This one uses spell points.

**Comment by misthero** [comment]
thx, understood, I'll try to fix that.

**Comment by misthero** [comment]
I have removed the first message, the second one is the default from the dnd5e system.

**Comment by misthero** [comment]
> Is there a way that I could assign certain PCs to use spell points or spell slots so that the module knows when to put up a dialogue box?

try the new version, let me know if i't better
