### ISSUE TITLE
All Spells cost 0 Spell Points

### ISSUE THREAD

**Issue by HeringtonPress** [misthero/dnd5e-spellpoints#85]
Spells of all levels always cost 0 SP regardless of what I have the cost set to. I've tried changing the cost in the individual Spell Point item and the Module settings but it all seems to have no effect.

![image](https://github.com/misthero/dnd5e-spellpoints/assets/93562930/e3f687fa-a035-4d5e-80f8-a0533687b669)

**Comment by misthero** [comment]
thankyou, I'm checking what changed in the latest dnd v3.2 update about spell casting.

**Comment by misthero** [comment]
one question, are you on v12?

**Comment by misthero** [comment]
thx, I've published an update, let me know if it works for you

**Comment by TheDunlop** [comment]
Works like a charm! Great work, and timely, too; thanks very much for your efforts. Feel free to mark the issue as resolved!
