### ISSUE TITLE
Spell Points not consumed on cast (all costs read as 0-pt)

### ISSUE THREAD

**Issue by TheDunlop** [misthero/dnd5e-spellpoints#86]
As of 5e v3.2.0 and Foundry v12 Stable (Build 324), it seems as though the module no longer consumes Spell Points on cast. Here are the steps I followed to replicate the issue:

1. Create a new world with only the Spell Points module installed and enabled.
2. Create a blank test scene (and a light source, so our lil wizard can see).
3. Create a Test Wizard actor at level 1, grant him Burning Hands from the SRD, and place him on the test scene.
4. Perform a Long Rest so the poor lil guy gets some spell slots, then cast Burning Hands as normal.
5. Drag the Spell Points item from the compendium onto the Test Wizard, enabling Spell Points for him.
6. Note that the message reads "Cast at Level... 1st Level (Costs 0 Spell Points)" as shown below.
7. Cast the spell as normal, noting that the Wizard's spell points do not decrease, remaining at 4/4.

![image](https://github.com/misthero/dnd5e-spellpoints/assets/38591680/5cbba71d-9678-48df-9837-0646e563ac84)

I have the default, non-custom Spell Points preset enabled, and automatic progression is enabled as well:
![image](https://github.com/misthero/dnd5e-spellpoints/assets/38591680/0c574950-c935-4c4e-b3c7-ea48b7fd511f)

Even when DMG (Custom) is selected and the costs for each spell level are manually set, it still costs 0 SP to cast a spell at any level. It's still usable, of course; you just need to manually edit your SP after each spell-cast, but this seems a core functionality of the module so I figured I'd report it!

**Comment by misthero** [comment]
thx for reporting it and the details provided, I will work on a solution, anyway this is duplicated issue.

https://github.com/misthero/dnd5e-spellpoints/issues/85
