### ISSUE TITLE
Spell Points Consumption bug

### ISSUE THREAD

**Issue by Dprime84** [misthero/dnd5e-spellpoints#89]
Not quite sure what broke the add-on, however as of right now, if i have no spell slots set up for the caster 
![image](https://github.com/misthero/dnd5e-spellpoints/assets/171746980/f30d9d33-9d13-4144-83b2-bee97e4b7472)
i get this window when trying to cast a spell:
![image](https://github.com/misthero/dnd5e-spellpoints/assets/171746980/05d221d9-2285-4bca-b2be-bf723df016c1)
the issue is twofold: a) i cannot upcast b) no spell points get consumed ever

Soon as I restore spell slots to how they were:
![image](https://github.com/misthero/dnd5e-spellpoints/assets/171746980/ac757634-957c-4743-87d6-0ae10ee23c49)
i only get this option when casting spells:
![image](https://github.com/misthero/dnd5e-spellpoints/assets/171746980/a1ce472c-d0bd-46a3-a7d4-d89e2a2fbfbc)
Same applies when the slots are available. 
I am going out of my mind cause these things were working fine before but suddenly stopped and I can't for the life of me work out why. I've disabled all recently downloaded addons and the issue persists. I am running foundry v 11.315, dnd 3.2.0 and add on v 2.2.2.
Any ideas what might be causing this?

**Comment by misthero** [comment]
hello @Dprime84 
yes I think I know what is happening, version 2.2.2 is not compatible with foundry v11, did you installed manually? try using this version instead:
https://github.com/misthero/dnd5e-spellpoints/releases/tag/v2.2.15

this one should support both dnd3.2 and foundry v11

please let me know if it works for you

**Comment by Dprime84** [comment]
I think I may have accidentally forced the update through when the platform notified me about the manifesto url change. Tried using the link for 2.2.15 but then got an error saying that's only compatible with v12. Switched server to v12 and now a whole bunch of other add-ons broke...fml 🥲

**Comment by misthero** [comment]
that's strange, v 2.2.15 is only for v11

![immagine](https://github.com/misthero/dnd5e-spellpoints/assets/3662610/85e05558-cb02-4efd-9ae5-bead1a783ff6)

do you have a backup of your world?

**Comment by Dprime84** [comment]
I do but with a whole load of work missing. I'm either gonna have to count on the other important addons to update or redo a load of work heh. Serves me right for not backing up before running updates...

**Comment by misthero** [comment]
I'm very sorry, I know what that means...

**Comment by Dprime84** [comment]
Have only myself to blame for obsessive updating heh. What's the old saying? If it ain't broke, don't fix it? Yeah. Note to self for the future haha
