### ISSUE TITLE
Spell Points that should restore on Long Rest instead go down when Long Resting

### ISSUE THREAD

**Issue by ExileofBrokenSky** [misthero/dnd5e-spellpoints#9]
### So first off, I isolated the mod and made a fresh empty DND5e world to help narrow things down.

![image](https://user-images.githubusercontent.com/28786777/104946607-59af0a00-5988-11eb-8d22-6aea83406837.png)

### My configuration is slightly modified from the default

![image](https://user-images.githubusercontent.com/28786777/104946720-8f53f300-5988-11eb-8a65-8523d48f5f9a.png)

### Here's the issue:

![image](https://user-images.githubusercontent.com/28786777/104946880-cde9ad80-5988-11eb-95e6-6ed83905e9f1.png)

This character has no spells in their spellbook.
On LR, for some reason it attempts to cast some mystery spell, and also doesn't restore the points. If I long rest with some points, it will cast the mystery spell still, deducting the points for that spell and still doesn't restore any points.  
LR should function how SR works.

This is the mystery spell in the console I think:

![image](https://user-images.githubusercontent.com/28786777/104947168-55372100-5989-11eb-89b6-2e42b4c36d86.png)

### Probably unrelated to the above issue, but can still become a different one:

![image](https://user-images.githubusercontent.com/28786777/104947597-ff16ad80-5989-11eb-9f90-675f7f9e26e2.png)

As an example, simply adding an item (or rearranging existing ones) the spell point system is getting called and filling up the console. Many different things besides that log to console. Constant logging (esp. of whole objects and collections) to the console can slow things down. Can only really feel it when multiple other mods and the core system are doing the same multiplied across all players, but it can be prevented. 

I suggest that if the logs are just for debugging, maybe create a boolean in the config to only print the logs when checked, and otherwise save the server's cycles. If every mod author could do this it would help contain console bloat.

**Comment by misthero** [comment]
Yep you are right, there are too many logs, that is a leftover from the latest patches, I rushed those a little an forgot to remove.

More intresting is the other issue I'm going to investigate, meanwhile, what happens if the character has spells?

The module doesn't really do (or shoudn't do anything) when you LR or SR since that is just a regular, default resource the module read when you cast.. things are even weirder since you say it just happen with Long Rest and not with short .
I'll let you know what I discover. Thank you.

**Comment by ExileofBrokenSky** [comment]
Did some digging and looks like it might just be a bug with the core system, lol

https://gitlab.com/foundrynet/dnd5e/-/issues/928

**Comment by misthero** [comment]
I confirm. That is. 

Next patch will remove the extra logs in console anyway.

Thank you.
