### ISSUE TITLE
Error When Installing

### ISSUE THREAD

**Issue by Kharmans** [misthero/dnd5e-spellpoints#90]
When installing the module, Foundry throw this error
![image](https://github.com/misthero/dnd5e-spellpoints/assets/112586547/6e277d7f-f472-4c9b-973d-515d9d26ae0f)

And I can't even install it manually cause you don't have a link for that (or I can't find it).

**Comment by Kharmans** [comment]
I managed to install manually, but this error is still showing when trying to install from the Foundry Module List.

**Comment by misthero** [comment]
thx for the heads up, there is a typo in the url I gave to foundry, it's "modue.json" not "module.jsonle.json" .... my bad..

**Comment by misthero** [comment]
should be fixed now
