### ISSUE TITLE
Foundry v12 - unsupported core version

### ISSUE THREAD

**Issue by ZeeShinister** [misthero/dnd5e-spellpoints#92]
The module no longer loads at all since Foundry v12, fyi. Please update (when you have the time, of course). :)

(And thank you for this module, it is a staple for all my games.) <3

**Comment by misthero** [comment]
it's about 3 weeks since the module is compatible with v12 what version do you have installed? do you see any error in browser console?

**Comment by ZeeShinister** [comment]
It is V12 build 327 - and it seems to have fixed itself. Thank you for the reply, tho! :)
