### ISSUE TITLE
[BUG] 0 Spell Points Coast

### ISSUE THREAD

**Issue by Kharmans** [misthero/dnd5e-spellpoints#95]
When trying to cast any spell, 0 Spell Points are consumed and this error is showed on console.

![image](https://github.com/misthero/dnd5e-spellpoints/assets/112586547/cd08cfcc-232b-44f5-bb70-7c122e694fb5)

**Foundry**: v12.327
**D&D5e**: 3.2.1
**Advanced Magic - Spell Points System 5e**: v2.2.1

**Comment by misthero** [comment]
You should update Advanced Magic - Spell Points System 5e to 2.2.20

**Comment by Kharmans** [comment]
Oh, sorry. The module was locked. I test in v2.2.20 and it's working fine.
