### ISSUE TITLE
Module doesn't seem to work

### ISSUE THREAD

**Issue by Abandonpuppy** [misthero/dnd5e-spellpoints#97]
Hello,

I'm trying to use your module, but It doesn't change the character sheet or ask for spell point usage. I'm using v12 and the most recent versions of your module and DND. Please see below. I'm not sure what steps I need to take to get his working. Thank you in advance.

<img width="395" alt="Spell Points Error 2" src="https://github.com/misthero/dnd5e-spellpoints/assets/149509755/30621252-f711-4b76-b07d-73020ef319e3">
<img width="395" alt="Spell Points Error 1" src="https://github.com/misthero/dnd5e-spellpoints/assets/149509755/f37401af-2ac2-4792-9d36-a8376d6eb738">

**Comment by misthero** [comment]
hello, I need more details, can you give me the version of the module you are using?

also please open the console (F12) and, while it is open try to repeat the steps, remove the spellpoints item, drag it again on the sheet, try to cast a spell. Do you see any error in the console?

![immagine](https://github.com/misthero/dnd5e-spellpoints/assets/3662610/65e40860-24c9-4a74-ab41-e1dc60a68fdf)

**Comment by Abandonpuppy** [comment]
Of course. 

I'm using Advanced Magic version 2.2.20. 
DnD 5E version 3.2.1
Foundry Version 12, Build 327

I don't know if they are connected. But under spell points, I see the following errors.

<img width="421" alt="Spell Points Error 6" src="https://github.com/misthero/dnd5e-spellpoints/assets/149509755/49678db8-20c1-4954-96f6-f23dc26b50af">
<img width="421" alt="Spell Points Error 5" src="https://github.com/misthero/dnd5e-spellpoints/assets/149509755/47ff5836-de26-4310-afc9-42eab9dc319f">
<img width="418" alt="Spell Points Error 4" src="https://github.com/misthero/dnd5e-spellpoints/assets/149509755/ce798b9e-11ac-4987-bb2b-800e577f392b">
<img width="423" alt="Spell Points Error 3" src="https://github.com/misthero/dnd5e-spellpoints/assets/149509755/2f1aa61a-2817-44ad-a4cd-7159feacb34d">

**Comment by misthero** [comment]
I can see you are having problem with other things, those, at least the first 2 or 3 screenshots looks like errors with some macro.

Can you try making a test world without any module but spellpoints and check if it works there?

**Comment by Abandonpuppy** [comment]
I apologize for wasting your time. After running a test server, I realize it has nothing to do with the module. Thank you for your help!

**Comment by misthero** [comment]
no problem, glad to help
